services:
  - type: web
    name: doc-generator
    env: go
    plan: free
    rootDir: project-backend
    buildCommand: go build -o app
    startCommand: ./app
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8090
    autoDeploy: true
    branch: main
    repo: [https://github.com/aliisayev/doc-generator.git](https://github.com/aliisayev/doc-generator.git)